# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Michael Franke
title: Bayes, pragmatics, evolution etc.
email: mchfranke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  assorted musings and ramblings about language, sience, philosophy of language and science and all that
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: meanwhileina
github_username:  michael-franke
permalink: /blog/:year/:month/:day/:title


# Build settings
markdown: kramdown
