---
layout: post
title: "Computing Bayes Factors"
date:   2017-03-20
categories: statistics, modeling
status: process
published: false
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
require('tidyverse')
require('reshape2')
require('coda')
require('ggmcmc')
require('rjags')
require('runjags')
```

<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>

look at data

```{r}
y = c(.94, .77, .40, .26, .24, .16)
t = c(  1,   3,   6,   9,  12,  18)
obs = y*100
```

look at a model

```{r, results='hide', warning=FALSE, message=FALSE, echo = FALSE}


modelString = "
model{
  m ~ dbern(0.5)
  a ~ dunif(0,1.5)
  b ~ dunif(0,1.5)
  c ~ dunif(0,1.5)
  d ~ dunif(0,1.5)
  for (i in 1: 6){
    pT[i] = ifelse(m == 0, a*exp(-t[i]*b), c*t[i]^(-d))
    p[i] = min(max( pT[i], 0.0001), 0.9999)
    obs[i] ~ dbinom(p[i], 100)
  }
}"
# prepare for JAGS
dataList = list(obs = obs, t = t)
# set up and run model
jagsModel = jags.model(file = textConnection(modelString), 
                       data = dataList,
                       n.chains = 2)
update(jagsModel, n.iter = 50000)
codaSamples = coda.samples(jagsModel, 
                           variable.names = c("m", "a", "b", "c", "d"),
                           n.iter = 5000)
ms = ggs(codaSamples)
wideSamples = dcast(ms, Iteration + Chain ~ Parameter)
```